app = "musicbot-rfsieg"
primary_region = "fra"

[build]

[processes]
  app = "python bot.py"

[mounts]
  source = "musicbot_data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  auto_stop_machines = false
  auto_start_machines = false
